@baseUrl = http://localhost:3001
# @baseUrl = https://fullstackopen-part3-patient-glitter-555.fly.dev

GET {{baseUrl}}/api/persons

###
GET {{baseUrl}}/info

### Get a person
GET {{baseUrl}}/api/persons/66cb61284531433bf01c3f84

### Get a person with missing id
GET {{baseUrl}}/api/persons/66cb4b2236ae537933e651bs

### 
DELETE  {{baseUrl}}/api/persons/66d99e98cde83511dcf2922c

###
POST {{baseUrl}}/api/persons
Content-Type: application/json

{
    "name": "aaa",
    "number": "0869"
}